baseURL = "https://harunohi88.github.io/"
languageCode = "ko-kr"
title = "harunohi devlog"
theme = "PaperMod"

[params]
  author = "harunohi"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
